#!/bin/sh

# Copyright (c) 2013 Michael Hartl
# Released under the MIT License (http://opensource.org/licenses/MIT)

# Syncs the local master branch with remote.
CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
git checkout master
git pull
git checkout $CURRENT_BRANCH
