#!/bin/sh

# Copyright (c) 2013 Michael Hartl
# Copyright (c) 2013 Aleksandar Simic
# Released under the MIT License (http://opensource.org/licenses/MIT)

# Opens the remote page for the repo (OS X only).
URL=`git config --get remote.origin.url`
GIT_PATTERN='s/(.*)@(.*):(.*)/https:\/\/\2\/\3/'
echo $URL | sed -E $GIT_PATTERN | sed 's/\.git//' | xargs open
