#!/bin/bash

# Copyright (c) 2013 Michael Hartl
# Released under the MIT License (http://opensource.org/licenses/MIT)

# Deletes the remote branch on origin if it is safe to do so.
OUT=`git log ..origin/$1`
if [[ $OUT != "" ]]; then
  printf '%s\n'
  echo ">>>>> ERROR -- Cannot auto-delete remote branch! <<<<<"
  echo "Target branch contains unmerged commits. Please cherry-pick the commits or merge the branch again."
  echo "Exiting..."
  printf '%s\n'
  exit 0
else
  git push origin :$1
fi