#!/bin/bash

# Copyright (c) 2013 Michael Hartl
# Released under the MIT License (http://opensource.org/licenses/MIT)

# Opens the remote page for the repo (OS X only).
URL=`git config --get remote.origin.url`
GIT_PATTERN='s/git@(.*):(.*)/https:\/\/\1\/\2/' 
echo $URL | sed -E $GIT_PATTERN | sed 's/(\.git)//' | xargs open 
